In [3]:
import tensorflow as tf

# 텐서플로우의 기초 ! 텐서 자료형입니다
# 숫자 ,리스트를 담을수 있습니다.
tenser = tf.constant(3)
print(tenser)

tf.Tensor(3, shape=(), dtype=int32)


In [5]:
텐서 = tf.constant([1,2,3])
print(텐서)


tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [11]:
텐서2 = tf.constant([4,5,6])
print(tf.add(텐서,텐서2))

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [22]:
텐서3 = tf.constant([[1,2], 
                     [3,4]],tf.float32)
# 행렬모양임
# (1,2 )
# (3,4 )

# 뒤에서부터 해석
# 3행 2열 이 2개  
텐서4 = tf.zeros([2,2,3])

print(텐서4.shape) 
print(텐서4) 
print(텐서3) 



(2, 2, 3)
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 2, 3), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [25]:
# 가중치는 variable
w = tf.Variable(1.0)
print(w)
w.assign(2.0)
print(w)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>
