In [2]:
import tensorflow as tf
import numpy as np
print(tf.__version__)
# COVID-19 Detection using VGG-16

2.9.2


In [3]:
# 설치된 패키지목록 만들기
# !pip freeze > requirements.txt

In [4]:
# tf.range() 는 기존 파이썬 range() 와 비슷함
a = tf.range(0,3)
b = tf.range(1,5,2)
c = list(range(1,10,2))

print (a)
print (b)
print (c)

tf.Tensor([0 1 2], shape=(3,), dtype=int32)
tf.Tensor([1 3], shape=(2,), dtype=int32)
[1, 3, 5, 7, 9]


In [5]:
# linespace 는 주어진 범위를 균일한 간격으로 나누는 숫자의 시퀀스반환 
a = tf.linspace(0,1,3)
b = tf.linspace(0,3,10)
c = np.linspace(0,1,3)

print(a)
print(b)

print("---------------")
print(c)

tf.Tensor([0.  0.5 1. ], shape=(3,), dtype=float64)
tf.Tensor(
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ], shape=(10,), dtype=float64)
---------------
[0.  0.5 1. ]


In [6]:
# a+b
a = tf.add(1,2)
print(a)
# a-b
b= tf.subtract(10,5)
print(b)



tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


In [7]:
# 텐서를 넘파이 어레이로 변환
a = tf.constant([1, 2, 3])

print(a)
a= np.array(a)
print(a)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
[1 2 3]


In [8]:
# 넘파이 어레이를 텐서로 변환
b= np.ones(3)
print(b)
print(tf.multiply(b,3))

[1. 1. 1.]
tf.Tensor([3. 3. 3.], shape=(3,), dtype=float64)
